# This file needs LF line endings to work correctly on Windows.  If you are using Windows, please change the line endings to LF.


# User 65532 is a well-known and documented UserID created as part of the Chainguard base image.
# Using this ID is preferred to creating a new one
ARG CHAINGUARD_USER_AND_GROUP=65532

# Adding both FROM statements to the top of the file allows us to re-use the name/alias for the image.
# This promotes better readability, maintainability, and consistency across the Dockerfile.
FROM cgr.dev/optum.com/python:3.14 AS final
FROM cgr.dev/optum.com/python:3.14-dev AS build

ARG CHAINGUARD_USER_AND_GROUP

USER root

# Create and set permissions for shared data directory
RUN mkdir -p /shared_data && chown ${CHAINGUARD_USER_AND_GROUP}:${CHAINGUARD_USER_AND_GROUP} /shared_data
WORKDIR /app

# Create a root folder for the apk install; this needs to be from the prod image
COPY --from=final / /prod

# Create and activate virtual environment properly
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Use Central timezone
ENV TZ=America/Chicago

# Install dependencies in the venv during build stage
RUN <<ER_AUTHENTICATION_BLOCK

apk add --no-cache syft
apk add --no-cache --initdb --root /prod curl

ER_AUTHENTICATION_BLOCK

# # --------------------------------------------------------------------
# # Final stage - keep the original base image as requested
# FROM final

# # IMPORTANT: Re-import ARGs in the final stage
# ARG CHAINGUARD_USER_AND_GROUP

# # Import apk packages from build stage
# COPY --from=build /prod /

# WORKDIR /app

# # Set the system locale to UTF-8 encoding to prevent encoding errors when reading/writing files or string
# ENV LANG=C.UTF-8

# # Disable Python .pyc bytecode cache files; bytecode caching provides no benefit since the image is immutable
# ENV PYTHONDONTWRITEBYTECODE=1

# # Disable output buffering for stdout and stderr so that logs are written in realtime
# ENV PYTHONUNBUFFERED=1

# # Set path information
# ENV PATH="/opt/venv/bin:$PATH"
# ENV PYTHONPATH="/app"

# # Use Central timezone
# ENV TZ=America/Chicago

# # Expose port for web service
# EXPOSE 8000
