services:
  service:
    image: anchore-search:latest
    build:
      context: .
      dockerfile: dockerfile
      secrets:
        - jf-user
        - jf-token

secrets:
  jf-user:
    environment: ER_AUTH_USER
  jf-token:
    environment: ER_AUTH_TOKEN
